### ISSUE TITLE
Add support for Avro Subject Naming Strategy

### ISSUE THREAD

**Issue by maarek** [PandoraMedia/kbrowse#32]
Since a Kafka Topic can contain Avro messages that are serialized using different schemas, the default naming strategy of "topic-key" and "topic-value" forces support for 1 Avro schema per topic. Provide a configuration to set an alternate naming strategy as described in the Kafka documents below. 

[https://docs.confluent.io/current/schema-registry/docs/serializer-formatter.html#subject-name-strategy](https://docs.confluent.io/current/schema-registry/docs/serializer-formatter.html#subject-name-strategy)

**Comment by maarek** [comment]
This is not needed as schema is resolved by ID and not name and only publishing uses the naming strategy. My bad!

**Comment by ptuckey** [comment]
Thanks for bringing this up - I hadn't considered it before.
